# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt

        # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
                entity:
                    class: AppBundle:Usuario
                    property: nomusuario

    firewalls:
        login:
            pattern: ^/login$
            anonymous: ~
        default:
            pattern: .*
            security: true
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: control_redirect
            logout:
                path: logout
                invalidate_session: true
                target: login

        admin:
            pattern: ^/admin/
            security: true
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: principal
            logout:
                path: logout
                invalidate_session: true
                target: login

        doc:
            pattern: ^/doc/
            security: true
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: docprincipal
            logout:
                path: logout
                invalidate_session: true
                target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMINISTRADOR }
        - { path: ^/doc, roles: ROLE_DOCENTE }