<?php

namespace AppBundle\Entity;

/**
 * MatriculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriculaRepository extends \Doctrine\ORM\EntityRepository
{
    public function matriculasActivas($carnet)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Matricula m WHERE m.alumnoCarnetalumno = :carnet AND m.esactivo = :activo'
        )
        ->setParameter('carnet',$carnet )
        ->setParameter('activo',1)
        ->getSingleResult();
    }
    public function fechaReciente($carnet)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT MAX (m.fechamatricula) FROM AppBundle:Matricula m WHERE m.alumnoCarnetalumno = :carnet'
        )
            ->setParameter('carnet',$carnet)
            ->getSingleResult();
    }
    public function matriculasReciente($fecha)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Matricula m WHERE m.fechamatricula = :fecha'
        )
            ->setParameter('fecha',$fecha )
            ->getSingleResult();
    }
    public function alumnosmMatriculados()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Matricula m WHERE m.esactivo = :activo ORDER BY m.nivelnivel ASC '
        )
            ->setParameter('activo',1 )
            ->getResult();
    }
}
