<?php

namespace AppBundle\Entity;

/**
 * ModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloRepository extends \Doctrine\ORM\EntityRepository
{
    public function verificarModulo($fecha)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Modulo m WHERE m.fechainicio < :fecha AND m.fechafin > :fecha'
        )
            ->setParameter('fecha',$fecha )
            ->getOneOrNullResult();
    }
}
