<?php

namespace AppBundle\Entity;

/**
 * NivelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelRepository extends \Doctrine\ORM\EntityRepository
{
    public function nivelesColocacion()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Nivel m WHERE m.idnivel != :carnet ORDER BY m.idnivel ASC'
        )
            ->setParameter('carnet',1 )
            ->getResult();
    }
}
