<?php

namespace AppBundle\Entity;

/**
 * RecordAlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordAlumnoRepository extends \Doctrine\ORM\EntityRepository
{
    public function numeroNotas($nota)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT COUNT(r.idrecordalumno)FROM AppBundle:Recordalumno r WHERE r.notafinal = :activo'
        )
            ->setParameter('activo',$nota )
            ->getSingleScalarResult();
    }
}
