<?php

namespace AppBundle\Entity;

/**
 * RecordAlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordAlumnoRepository extends \Doctrine\ORM\EntityRepository
{
    public function numeroNotas($nota)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT COUNT(r.idrecordalumno)FROM AppBundle:Recordalumno r WHERE r.notafinal >= :nota AND r.notafinal < :notaA'
        )
            ->setParameter('nota',$nota )
            ->setParameter('notaA',$nota+1 )
            ->getSingleScalarResult();
    }
    public function conNota($nota)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT r FROM AppBundle:Recordalumno r WHERE r.notafinal = :nota'

        )
            ->setParameter('nota',$nota )
            ->getResult();
    }
    public function prueba($nota,$nivel){
        return $this->getEntityManager()->createQuery(
            'SELECT COUNT(ra.alumnoCarnetalumno) FROM AppBundle:Recordalumno ra, AppBundle:Record r
             INNER JOIN r.recordalumnorecordalumno rai
             WHERE ra.notafinal = :nota AND r.nivelnivel = :nivel'
        )   ->setParameter('nota',$nota)->setParameter('nivel',$nivel)
            ->getResult();
    }
}
